apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  channel: stable-4.18
  clusterID: d61fd2e3-6195-48f0-8cc0-81e84a1f0edf
  desiredUpdate:
    image: quay.io/openshift-release-dev/ocp-release@sha256:349912ef80ff71bdb591b36d8b3eca9df2446fa2497af08058d1777b8e0cf3ca
    version: 4.18.30
