apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- longhorn.yaml
- rbac

patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: longhorn-ui
        namespace: longhorn-system
      spec:
        template:
          spec:
            containers:
            - name: longhorn-ui
              volumeMounts:
                - name: nginx-log
                  mountPath: /var/log/nginx
                - name: nginx-lib
                  mountPath: /var/lib/nginx
            volumes:
              - name: nginx-log
                emptyDir: {}
              - name: nginx-lib
                emptyDir: {}
