apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
commonLabels:
  app.kubernetes.io/name: vault

resources:
- namespace.yaml
- serviceaccount.yaml
- rbac.yaml
- vault.yaml
- vault-allow-vault-scc.yaml
- vault-ingress-service.yaml
- route.yaml
- backup-job

configurations:
  - namespace-transformer.yaml
