apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    nerc.mghpcc.org/aggregate-to-nerc-ops: "true"
  name: nerc-ops-machineconfig-reader
rules:
  - apiGroups:
      - machineconfiguration.openshift.io
    resources:
      - machineconfigs
    verbs:
      - list
      - get
      - watch
