apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hostpath-provisioner-operator
subjects:
  - kind: ServiceAccount
    name: hostpath-provisioner-operator
    namespace: hostpath-provisioner
roleRef:
  kind: ClusterRole
  name: hostpath-provisioner-operator
  apiGroup: rbac.authorization.k8s.io
