apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan-2175-nese
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
    - name: bond0.2175
      type: vlan
      state: up
      ipv4:
        enabled: true
        dhcp: true
        auto-routes: true
      vlan:
        base-iface: bond0
        id: 2175
      mtu: 9000
