apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- ../../base/operator.openshift.io/ingresscontrollers/default
- ../../base/config.openshift.io/apiservers/cluster

patches:
- path: patches/custom_ingress_certificate.yaml
- path: patches/custom_apiserver_certificate.yaml
