apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: lb-is-metallb
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            lb-is-metallb: "true"
