apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: hosted-clusters
  namespace: clusters
spec:
  clusterSets:
  - default
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: hosted-cluster
          operator: In
          values:
          - "true"
