apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: nfs-plus-csi-driver
resources:
  - ../csi-driver-nfs
  - ../../base/storage.k8s.io/storageclasses/nfs-plus-csi-driver
