apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: backup-vault-template
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: backup-vault-run-
    spec:
      serviceAccountName: backup-job
      taskRef:
        name: backup-vault
      workspaces:
        - name: snapshots
          persistentVolumeClaim:
            claimName: vault-snapshots
        - name: backup-job
          secret:
            secretName: vault-backup-s3-endpoint
        - name: backup-scripts
          configMap:
            name: backup-scripts
        - name: vault-tls
          secret:
            secretName: vault-tls
