apiVersion: batch/v1
kind: Job
metadata:
  name: trigger-configure-vault
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 86400

  template:
    spec:
      restartPolicy: Never
      serviceAccountName: vault
      containers:
        - name: trigger-configure-vault
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli
          command:
          - /bin/bash
          - -c
          - |
            oc create job --from=cronjob/configure-vault configure-vault-triggered-"$RANDOM"
