apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../../base/openapi
- ../../base/core/configmaps/admin-acks/
- ../../base/machineconfiguration.openshift.io/kubeletconfigs/system-reserved
- ../../base/config.openshift.io/oauths/cluster
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/self-provisioners
- ../../bundles/cert-manager
- ../../bundles/external-secrets
- ../../bundles/external-secrets-clustersecretstore
- ../../bundles/nmstate
- ../../bundles/acm
- ../../bundles/group-sync-operator
- ../../bundles/openshift-gitops
- ../../base/operator.openshift.io/networks/cluster
- clusterissuers
- certificates
- console
- groupsyncs
- clusterrolebindings
- hostpath-provisioner

components:
  - ../../components/nerc-oauth-github
  - ../../components/nerc-certificate-issuer
  - ../../components/custom-certificates

configMapGenerator:
- name: admin-acks
  namespace: openshift-config
  behavior: merge
  literals:
    - ack-4.11-kube-1.25-api-removals-in-4.12=true
    - ack-4.12-kube-1.26-api-removals-in-4.13=true
    - ack-4.13-kube-1.27-api-removals-in-4.14=true

patches:
- path: clustersecretstores/nerc-cluster-secrets_patch.yaml
- patch: |
    apiVersion: config.openshift.io/v1
    kind: OAuth
    metadata:
      name: cluster
    spec:
      identityProviders:
      - name: github
        github:
          clientID: 1a8790fb1d1c5f46c510
- target:
    kind: ExternalSecret
    name: github-client-secret
  patch: |
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: nerc/hypershift1/openshift-config/github-client-secret
- target:
    kind: ExternalSecret
    name: aws-route53-credentials
  patch: |
    - op: replace
      path: /spec/dataFrom/0/extract/key
      value: nerc/hypershift1/aws-route53-credentials
- target:
    kind: APIServer
    name: cluster
  patch: |
    - op: replace
      path: /spec/servingCerts/namedCertificates/0/names/0
      value: api.hypershift1.int.massopen.cloud
- target:
    kind: ExternalSecret
  patch: |
    - op: replace
      path: /spec/secretStoreRef
      value:
        kind: ClusterSecretStore
        name: nerc-cluster-secrets
- target:
    kind: ExternalSecret
    name: aws-route53-credentials
  patch: |
    - op: add
      path: /metadata/namespace
      value: openshift-operators
    - op: replace
      path: /spec/dataFrom/0/extract/key
      value: nerc/hypershift1/openshift-operators/aws-route53-credentials
- patch: |
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
        name: acm
    spec:
        channel: release-2.8
- patch: |
    apiVersion: multicluster.openshift.io/v1
    kind: MultiClusterEngine
    metadata:
      name: multiclusterengine
    spec:
      overrides:
        components:
        - enabled: true
          name: hypershift-preview
- patch: |
    apiVersion: metal3.io/v1alpha1
    kind: Provisioning
    metadata:
      name: provisioning-configuration
    spec:
      watchAllNamespaces: true
- patch: |
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: acm
      namespace: open-cluster-management
    spec:
      channel: release-2.9
- patch: |
    apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: openshift-gitops-operator
      namespace: openshift-operators
    spec:
      channel: gitops-1.10
