apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/openapi
- ../../base/core/configmaps/admin-acks/
- ../../base/machineconfiguration.openshift.io/kubeletconfigs/system-reserved
- ../../base/config.openshift.io/oauths/cluster
- ../../base/rbac.authorization.k8s.io/clusterroles/node-labeler/
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/self-provisioners
- ../../bundles/cert-manager
- ../../bundles/openshift-operators-redhat
- ../../bundles/cluster-admin-rbac
- ../../bundles/external-secrets
- ../../bundles/nmstate
- ../../bundles/console
- ../../bundles/image-registry
- ../../bundles/logging
- ../../bundles/group-sync-operator
- ../../base/operator.openshift.io/networks/cluster
- clusterrolebindings/nerc-ops-cluster-reader.yaml
- clusterrolebindings/nerc-ops-sudoers.yaml
- clusterrolebindings/nerc-ops-portforward.yaml
- clusterrolebindings/nerc-logs-metrics-open-cluster-management-cluster-manager-admin.yaml
- groupsyncs
- machineconfigs

components:
- ../../components/custom-certificates
