apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-backup-s3-endpoint
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: vault-backup-s3-endpoint
    creationPolicy: 'Owner'
    deletionPolicy: "Retain"
    template:
      engineVersion: v2
  dataFrom:
    - extract:
        key: REPLACE IN OVERLAY
