apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
commonLabels:
  app.kubernetes.io/name: vault-backup-job

resources:
  - externalsecret.yaml
  - pvc.yaml
  - rolebinding.yaml
  - serviceaccount.yaml
  - task.yaml
  - trigger

configMapGenerator:
  - name: vault-backup-config
    options:
      disableNameSuffixHash: true
    envs:
      - vault-backup-config.env

  - name: backup-scripts
    options:
      disableNameSuffixHash: true
    files:
      - scripts/create-snapshot.sh
      - scripts/backup-to-s3.sh
      - scripts/cleanup-taskruns.sh
