apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: longhorn-allow-finalizers
rules:
- verbs:
    - '*'
  apiGroups:
    - longhorn.io
  resources:
    - engineimages/finalizers
    - nodes/finalizers
    - instancemanagers/finalizers
